datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: jdbc:h2:./ellas
  production:
    username: "${JDBC_DATABASE_USERNAME}"
    password: "${JDBC_DATABASE_PASSWORD}"
    url: "${JDBC_DATABASE_URL}"

ebean:
  migration:
    run: true